"use client";

import {
  LiveKitRoom,
  GridLayout,
  ParticipantTile,
  RoomAudioRenderer,
  ControlBar,
  useTracks,
  VideoConference
} from "@livekit/components-react";
import "@livekit/components-styles";
import { Track } from "livekit-client";

interface LiveKitGroupCallProps {
  /** The unique ID of the conversation room */
  roomName: string;
  /** JWT Token generated by your backend (Next.js server action/API route) */
  token: string;
  /** Your LiveKit Cloud / Self-hosted WebSocket URL */
  serverUrl: string;
  /** Callback triggered when the local user hits the "Leave" button */
  onLeave: () => void;
}

/**
 * A production-ready Group Video Call engine powered by LiveKit SFU.
 * 
 * NOTE: Ensure you have installed the required dependencies:
 * npm install livekit-client @livekit/components-react @livekit/components-styles
 */
export function LiveKitGroupCall({ roomName, token, serverUrl, onLeave }: LiveKitGroupCallProps) {
  return (
    <div className="fixed inset-0 z-[100] bg-zinc-950 flex flex-col items-center justify-center">
        {/*
          LiveKitRoom Provider: 
          Automatically manages the WebSocket connection, SFU negotiation, 
          WebRTC ICE tunneling, and hardware media track permissions.
        */}
        <LiveKitRoom
          video={true} // Auto-request camera
          audio={true} // Auto-request mic
          token={token}
          serverUrl={serverUrl}
          connect={true} // Auto-connect on mount
          onDisconnected={onLeave}
          className="relative w-full h-full flex flex-col"
          // Adding custom data-attributes or themes here if needed
          data-lk-theme="default"
        >
          {/* Custom Rendering Grid for all participants */}
          <div className="flex-1 w-full h-full overflow-hidden p-2 sm:p-4">
            <CustomGridEngine />
          </div>

          {/* Renders global audio streams so you can hear everyone */}
          <RoomAudioRenderer />

          {/* Bottom Controls Overlay (Mic, Camera, Screen Share, Leave) */}
          <div className="absolute bottom-6 left-1/2 -translate-x-1/2 z-50 bg-zinc-900/80 backdrop-blur-xl border border-zinc-800 rounded-3xl px-4 py-2 shadow-2xl">
            <ControlBar variation="minimal" />
          </div>
        </LiveKitRoom>
    </div>
  );
}

/**
 * CustomGridEngine:
 * Extracts tracking data directly from the SFU and natively renders
 * a responsive CSS grid that perfectly auto-scales based on the number
 * of participants connected to the room.
 */
function CustomGridEngine() {
  // Subscribe specifically to Camera and Screen Share tracks.
  // The 'withPlaceholder: true' ensures users who turn off their cameras still get a tile.
  const tracks = useTracks(
    [
      { source: Track.Source.Camera, withPlaceholder: true },
      { source: Track.Source.ScreenShare, withPlaceholder: false },
    ],
    { onlySubscribed: false }, // Render local + remote tracks
  );

  return (
    <GridLayout
      tracks={tracks}
      className="w-full h-[calc(100vh-120px)] gap-4 transition-all duration-300 ease-in-out"
    >
      {/* 
        ParticipantTile natively handles <video> tag mounting, handles "is speaking" 
        indicators, and provides a polished UI for each grid rectangle. 
      */}
      <ParticipantTile 
        style={{ 
            borderRadius: '1rem', 
            overflow: 'hidden', 
            boxShadow: '0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)',
            border: '1px solid rgba(255,255,255,0.05)'
        }} 
      />
    </GridLayout>
  );
}
